let name="Teja";
var a=20;
let s=true;
let b=100;
let ud;
let n=null;
const add=a+b;
const sub=a-18;
const mul=a*2;
const mod=a%5;
let gt=a>18;
let equal=a==b;
let ne=name=="Teja";
let and=a>=18&&s;
let or=a<=18||!s;
console.log(add);
console.log(sub);
console.log(mul);
console.log(mod);
console.log(gt);
console.log(equal);
console.log(ne);
console.log(and);
console.log(or);